openapi: 3.2.0
info:
  contact:
    email: support@altr.com
    name: API Support
  description: This is the API for managing Sidecars, Agents and their configurations.
  termsOfService: https://altr.com/info/altr-solutions-inc-terms-of-service/
  title: ALTR Sidecar/Agent Configuration Agents API
  version: 1.0.0
servers:
- url: https://{orgID}.sc-control.live.altr.com/v1
  variables:
    orgID:
      default: ''
tags:
- name: Agents
paths:
  /agents:
    get:
      description: List Agents for your organization.
      parameters:
      - description: The maximum number of items to return.
        in: query
        name: limit
        schema:
          default: 50
          maximum: 100
          minimum: 1
          type: integer
      - description: The Contiguous ID for pagination
        in: query
        name: contiguous_id
        schema:
          type: string
      - description: Filter by Agent type
        in: query
        name: type
        schema:
          enum:
          - SIS
          - CLASSIFIER
          type: string
      - description: Filter by Agent name in a `starts with` fashion. (Case-insensitive)
        in: query
        name: name_starts_with
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/management.ListAgentsOutput'
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fiber.APIError'
          description: Bad Request
        '429':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fiber.APIError'
          description: Bad Request
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fiber.APIError'
          description: Bad Request
      security:
      - basic: []
      summary: List Agents.
      tags:
      - Agents
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/agents.CreateAgentInput'
        description: Agent details.
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/management.Agent'
          description: Created
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fiber.APIError'
          description: Bad Request
        '429':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fiber.APIError'
          description: Bad Request
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fiber.APIError'
          description: Bad Request
      security:
      - basic: []
      summary: Create a new Agent.
      tags:
      - Agents
  /agents/{agent_id}:
    delete:
      description: An Agent cannot be deleted if its task_count > 0.
      parameters:
      - description: ID of Agent.
        in: path
        name: agent_id
        required: true
        schema:
          type: string
      responses:
        '204':
          description: No Content
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fiber.APIError'
          description: Bad Request
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fiber.APIError'
          description: Bad Request
        '429':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fiber.APIError'
          description: Bad Request
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fiber.APIError'
          description: Bad Request
      security:
      - basic: []
      summary: Delete Agent.
      tags:
      - Agents
    get:
      parameters:
      - description: ID of the Agent.
        in: path
        name: agent_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/management.Agent'
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fiber.APIError'
          description: Bad Request
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fiber.APIError'
          description: Bad Request
        '429':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fiber.APIError'
          description: Bad Request
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fiber.APIError'
          description: Bad Request
      security:
      - basic: []
      summary: Get an Agent.
      tags:
      - Agents
    patch:
      description: If property is not included it will not be updated. If property included with null value, it will be removed.
      parameters:
      - description: The Agent ID
        in: path
        name: agent_id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/agents.UpdateAgentInput'
        description: Details to update.
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/management.Agent'
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fiber.APIError'
          description: Bad Request
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fiber.APIError'
          description: Bad Request
        '429':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fiber.APIError'
          description: Bad Request
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fiber.APIError'
          description: Bad Request
      security:
      - basic: []
      summary: Update an Agent.
      tags:
      - Agents
components:
  schemas:
    agents.CreateAgentInput:
      properties:
        description:
          type: string
          x-order: '2'
        name:
          type: string
          x-order: '1'
        public_key_1:
          type: string
          x-order: '3'
        public_key_2:
          type: string
          x-order: '4'
        type:
          description: 'Valid types: SIS, CLASSIFIER'
          type: string
          x-order: '0'
      type: object
    management.PublicKey:
      properties:
        registered_at:
          type: string
        rsa_key:
          type: string
      type: object
      x-order: '9'
    fiber.APIError:
      properties:
        response:
          $ref: '#/components/schemas/fiber.APIErrorResponse'
        statusCode:
          type: integer
      type: object
    fiber.APIErrorResponse:
      properties:
        error_code:
          type: integer
        message:
          type: string
      type: object
    agents.UpdateAgentInput:
      properties:
        description:
          type: string
          x-order: '1'
        name:
          type: string
          x-order: '0'
        public_key_1:
          type: string
          x-order: '2'
        public_key_2:
          type: string
          x-order: '3'
      type: object
    management.Agent:
      properties:
        created_at:
          type: string
          x-order: '8'
        data_plane_url:
          type: string
          x-order: '4'
        description:
          type: string
          x-order: '3'
        id:
          type: string
          x-order: '1'
        name:
          type: string
          x-order: '2'
        public_key_1:
          $ref: '#/components/schemas/management.PublicKey'
        public_key_2:
          $ref: '#/components/schemas/management.PublicKey'
        task_count:
          type: integer
          x-order: '5'
        type:
          type: string
          x-order: '0'
        updated_at:
          type: string
          x-order: '9'
      type: object
    management.ListAgentsOutput:
      properties:
        agents:
          items:
            $ref: '#/components/schemas/management.Agent'
          type: array
          uniqueItems: false
          x-order: '0'
        contiguous_id:
          type: string
          x-order: '1'
      type: object
  securitySchemes:
    basic:
      scheme: basic
      type: http
externalDocs:
  description: ALTR Documentation
  url: https://docs.altr.com/?lang=en
